### PR TITLE
Added grammar check into CI

### PR DESCRIPTION
**Pull request by introkun**
- removed redundant docker-compose install in CI

## Description

# Checklist

- [ ] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [ ] Made any changes or additions to the documentation _where required_
- [ ] Changes generate no new warnings/errors
- [ ] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- ✨ Feature
- 🐛 Bug Fix
- 🚨 Breaking Change
- ♻️ Code Refactor
- 📝 Documentation Update

## Added/updated tests?

- 👍 yes
- 🙅 no, because they aren't needed
- 🙋 no, because **I need help**

## Related PRs, Issues etc
- Related Issue #
- Closes #

### CODE REVIEW

**Comment by introkun** [comment]
fixes #241

**Comment by introkun** [comment]
Done @TreyWW 
image
All tests passed in PR  https://github.com/introkun/MyFinances/pull/2

**Review by TreyWW — APPROVED** [review]

**Comment by introkun** [comment]
@TreyWW I see that you approved my change. Could you please also merge it?

**Comment by TreyWW** [comment]
Sorry I'll merge in the morning, just about to go to bed

**Pull request merged**
