### PR TITLE
Code refactored

### PR DESCRIPTION
**Pull request by Domejko**
## Description

Code cleanup/refactoring #160.
Insied **handler.py** in */tests* folder removed function:
```py
def cleanup_uploaded_files(files):
    """
    Cleanup uploaded files.

    Args:
        files (list): List of files to delete.
    """
    [file.delete() for file in files]
```
and changed `tearDown` accordingly:
```diff
- cleanup_uploaded_files([receipt.image for receipt in Receipt.objects.all()])
- cleanup_uploaded_files([pfp.profile_picture for pfp in UserSettings.objects.all()])

+ Receipt.objects.all().delete()
+ UserSettings.objects.all().delete()
```
Also `self.mock_images` form `ViewTestCase` class have been removed since it's not used anywhere in the code.

In **test_receipts.py** insied */tests/views* folder function call:
```py
create_mock_image()
```
have been replaced with:
```py
SimpleUploadedFile("mock_image.jpg", b"image_content", "image/jpeg")
```
to reduce additional steps in the process.

# Checklist

- [x] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [x] Made any changes or additions to the documentation _where required_
- [x] Changes generate no new warnings/errors
- [x] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- ♻️ Code Refactor

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #
- Closes #

### CODE REVIEW

**Comment by Domejko** [comment]
I wanted to get rid of it completely but **test_usersettings_profile_picture_post_with_valid** was failing and I didn't look for solution yet. But basically wanted to replace it and remove function to have less extra steps like creating image with PIL, using BytesIO, whole additional function when all could be handled directly just by `SimpleUploaderFile`. I know it's just a tests and it wont make any significant speed difference, but if it can be done then why not do it :)

**Comment by Domejko** [comment]
Of course if you want I can restore `create_mock_image` calls until I will be able to use `SimpleUploadedFile` for all tests and remove `create_mock_image`. Or restore `create_mock_image` and leave it as it is permanently.

**Comment by TreyWW** [comment]
Okay cool thats fine, just wanted a little clarity. Thanks

**Comment by TreyWW** [comment]
I'm still getting ` [Errno 13] The process cannot access the file because it is being used by another process` from the line
`instance.image.delete(save=False)`. Should we add the try blocks?

**Comment by Domejko** [comment]
This one it's just a cleanup/refactor PR so the error is still there. Today at late evening or tomorrow I will submit PR that is solving the issue of this bug/error from #173.

**Review by TreyWW — APPROVED** [review]

**Pull request merged**
