### PR TITLE
Feature/20 budgets dashboard layout

### PR DESCRIPTION
**Pull request by JonasFiechter**
---
title: Issue #20 | Budget dashboard creation
---

 

# Checklist

- [x] Ran the [Black Formatter]() on any new code (checks will fail without)
- [x] Made any changes or additions to the documentation where required
- [x] Changes generate no new warnings/errors
- [x] New and existing unit tests pass locally with my changes

## What type of PR is this?

- ✨ Feature
- ♻️ Code Refactor

## Description

As being a core component of a finance application, the following dashboard template gives for the next updates a good starting point to show for the users their most important billing information.

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #
- Closes #

### CODE REVIEW

**Review by TreyWW — APPROVED** [review]

**Comment by JonasFiechter** [comment]
Well, as the graph is kind of static, there are changes to be made with the JS, it is not responsive yet, etc.

Also, there are some basic math to be done to bring those dynamic values to the front. If there still discussion about the models, that can wait, otherwise we can keep working.

I think the cards into the grid are not wrapping yet as well.

To whatever tasks appear from here, I'm able to work on this weekend, back-end or front-end.

**Comment by JonasFiechter** [comment]
Hi @TreyWW , that's fine for me, as long as it works, we can use pure python, that's even better for me beause I know nothing about JS 🥇 hahaha;

I'll take a look into this library and make some tests, I just saw it can be installed with pip. If that's ok by your side, I can start working to make this work and adjust responsive layout, and when finish, we can discuss about mocking data, using static, etc... later on.

**Comment by TreyWW** [comment]
Sounds good! Thanks

**Comment by JonasFiechter** [comment]
Hi @TreyWW, took a while till I could get back to the code, Christmas, new year, and a lot of work...

I'll provide you a summary of the experience using Bokeh 3.x to provide a partial template and the JS we need to render the charts.

The whole Idea is promising but at the end of the day we would have so much work to change 'manually' the `<div>` that bokeh provides, using regex for adding more complex styling classes. I my opinion it has lots of mathematical and scientific tools to generate complex data visualization, but it provides a kind of unique style, which is not bad, but in our case seems like does not fit.

I'll share bellow how it looks so far. The usage is pretty simple, I created a component folder with the chart generator in it, and loaded the result which are a `div` and a `script` into the context through the view. And loaded them into the template with simple tags:

```
def generate_chart(income_data:list=[], expenses_data:list=[]): 
    # Generate random values
    days = ['Day ' + str(i) for i in range(1, 31)]
    income_data = [random.randint(1000, 2000) for _ in range(30)]
    expenses_data = [random.randint(500, 1000) for _ in range(30)]

    # Create a Bokeh figure
    p = figure(x_range=days, height=300, title="Income and Expenses",
               toolbar_location=None, tools="")

    # Plot income and expenses as vertical bars
    p.vbar(x=days, top=income_data, width=0.9, legend_label="Income",
           line_color="white", fill_color="rgba(75, 192, 192, 0.2)")

    p.vbar(x=days, top=expenses_data, width=0.9, legend_label="Expenses",
           line_color="white", fill_color="rgba(255, 99, 132, 0.2)")

    # Customize plot options
    p.xgrid.grid_line_color = None
    p.y_range.start = 0
    p.yaxis.axis_label = "Amount"

    # Convert Bokeh plot to components for embedding
    script, chart = components(p)

    chart = chart.replace('<div', '<div class="w-full h-full bg-gray-100 p-4"')
    print(chart)
    print(script)
    return script, chart
```
```
from backend.components.dashboard_chart import generate_chart

def dashboard(request: HttpRequest):
    script, chart = generate_chart()

    return render(request, "pages/dashboard.html", {
        'script': script,
        'chart': chart
    })
```


image

Please tell me if we should keep trying on this one, look that even using https://docs.bokeh.org/en/latest/docs/user_guide/styling/themes.html themes, customization would require keep using string methods like the `replace()` that I tried to use to change at least the background and make it grow into the parents div :laughing: . 

I saw other python options to generate these, we can look into then and keep testing, it is up to you my friend.

**Comment by TreyWW** [comment]
Hiya, yeah that looks like a great solution. That sounds fine by me. I'm going away so I'll likely not be responding for the next week, but feel free to still post comments or code. 
The graph does look good though, would be nice to not have the white background if you can figure out to make it transparent lol. 

Anyways, have a good Christmas.

**Comment by JonasFiechter** [comment]
Fine then, I'll work into making it fit with our current tailwind classes, don't worry about not answering, probably I'll continue when you come back :smile: 

Merry Christmas

**Pull request merged**
