### PR TITLE
Add test case for creating organization invoices

### LINKED ISSUE #188: [Enhance] Update test cases to work with both organizations + normal individual accounts
At the moment our tests only cover individual accounts. But now I'm working on #87 (teams) the ability to log into individual accounts and organization accounts is now a thing. This means we will struggle to find bugs and in general will be a mess.

Would be nice to get some tests in to also cover organization ability to do all of the same things as users. Also test cases for switching to organization and back to user, etc etc.

Some example test cases:
- Creating an invoice, make sure it creates on the account of the logged in user / logged in company
- Viewing all invoices, make sure you only view your logged in user/companies invoices
- Make sure users cannot create invoices under teams they don't belong in (member of or leader of)
- etc etc

Feel free to leave a comment if you would like to work on this. Make sure to ask for help if you would like to work on this but don't know how to start! :)

### PR DESCRIPTION
**Pull request by SBMOYO**
## Description

This pull request (PR) adds a new test case that covers scenarios related to invoice creation for organizations. It ensures that the process works correctly  and checks if the organization variable is set to the team that created the invoice.

##  Motivation and Context 
The motivation behind this change is to improve the accuracy of invoice creation within our system. By adding a specific test case and fixing the organization assignment, we ensure that invoices are associated correctly with the respective teams.

# Dependencies
No specific dependencies are required for this change.

# Checklist

- [x] Ran the Black Formatter and djLint-er on any new code.
- [x] Made necessary changes or additions to the documentation.
- [x] Ensured that changes generate no new warnings or errors.
- [x] Verified that new and existing unit tests pass locally with these changes.

## What type of PR is this?
- ✨ Feature (Test case addition)
- 🐛 Bug Fix (Fixing organization assignment)

## Added/updated tests?
- 👍 yes

## Related PRs, Issues
- Related Issue #188 
- Closes #188

### CODE REVIEW

**Review by TreyWW — CHANGES_REQUESTED** [review]
Hi there @SBMOYO,

Thank you for the PR, really appreciate it. Can the ENV_DIR directory be removed from the PR though please since it is committing ~40 files we don't need. 

Thanks

**Comment by TreyWW** [comment]
Hey @SBMOYO,

Did it definitely get removed, it still shows all files for me.

**Comment by SBMOYO** [comment]
how about now @TreyWW, Is it still there?

**Comment by TreyWW** [comment]
Oh right yeah, apologies for that. I'll look into this in about 20 mins. Thanks for pointing it out

**Comment by SBMOYO** [comment]
@TreyWW Thanks for pointing out the issue with the login team handler.

Regarding the other bug:
```python
AssertionError: 0 != 1 for self.assertEqual(len(invoices), 1)
```
If I update the code I like you suggested ```python invoices = Invoice.objects.filter(user=self.log_in_user.logged_in_as_team)``` the code raises a ValueError ```python ValueError: Cannot query "Team object (1)": Must be "User" instance```

I have a question, when a user creates an invoice as an individual the organisation variable is set to None. What value is the user variable set to when a user creates an invoice for an organisation, is it set to None just like what happens to organisation?

**Comment by TreyWW** [comment]
Sorry completely missed your message. Yep you're correct, if it's saving as an org then organisation is set to team object and user is none. And if setting under individual then user is the User object and organisation is none

**Review by TreyWW — APPROVED** [review]

**Comment by TreyWW** [comment]
Hi @SBMOYO,
Could you run `black .` again to format the files. Thanks

**Review by TreyWW — APPROVED** [review]

**Comment by TreyWW** [comment]
Thanks for the PR @SBMOYO! Really appreciate it.

**Pull request merged**
