### PR TITLE
initial setup fixes

### PR DESCRIPTION
**Pull request by introkun**
- removed generated bundle.js
- removed generated output.css
- updated tailwind build path
- updated gitignore to exclude environment.yml confing, output.css and bundle.js

## Description

# Checklist

- [ ] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [ ] Made any changes or additions to the documentation _where required_
- [ ] Changes generate no new warnings/errors
- [ ] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- ✨ Feature
- 🐛 Bug Fix
- 🚨 Breaking Change
- ♻️ Code Refactor
- 📝 Documentation Update

## Added/updated tests?

- 👍 yes
- 🙅 no, because they aren't needed
- 🙋 no, because **I need help**

## Related PRs, Issues etc
- Related Issue #
- Closes #

### CODE REVIEW

**Comment by introkun** [comment]
It's a bad practice to keep generated files in Git

**Comment by introkun** [comment]
How you will guarantee that someone will generate and add to Git a proper file?
Only generation (using CI) will help to address that

**Comment by TreyWW** [comment]
Yeah I'm fine with it being added through CI, just don't want to pass nothing to git that's all. Any ideas how I'd pass the generated files through Github Actions onto master?

**Comment by introkun** [comment]
You should keep generated files on the target server. You don't need to put it back to Git (even via CI)

**Comment by TreyWW** [comment]
Oh i guess it could be added when we run docker build, that'd probably be the best place to have it. It just needs to be passed with source before it reaches the server in our case cause we just pull and run there isn't really room for any extra commands

**Comment by introkun** [comment]
I can fix CI as well

**Comment by introkun** [comment]
I'm done @TreyWW.
All workflows ran successfully on my branch - https://github.com/introkun/MyFinances/pull/1
image

**Review by TreyWW — APPROVED** [review]
Absolutely incredible PR, thank you!

**Pull request merged**
