### PR TITLE
Dashboard's first template with sample

### PR DESCRIPTION
**Pull request by JonasFiechter**
---
 [IDEA] My Budget Dashboard layout #20 
---

--> [20] | Added layout structure and sample data to last commit

# Checklist

- [X] Ran the [Black Formatter]() on any new code (checks will fail without)
- [X] Made any changes or additions to the documentation where required
- [X] Changes generate no new warnings/errors
- [X] New and existing unit tests pass locally with my changes

## What type of PR is this?
- ✨ Feature

## Description

Adding to the last commit made withing wrong branch, this one has a little bit more structure and some styling to be evaluated.
As this step is all about UI/UX we'll need go back and forward with changes. So please fell free to request all kind of styling/structuring changes needed.

## Added/updated tests?
- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #
- Closes #

### CODE REVIEW

**Review by TreyWW — CHANGES_REQUESTED** [review]
Was this output file edited by you manually or our build command?

**Review by TreyWW — APPROVED** [review]
It's a great start, though I think we should improve the design slightly before we merge this in.

For a start, instead of purple could we use `primary`, this is a shade of blue, so it matches the rest of our colour theme, further more we should be using `card` instead of our own box, this also fits better with the rest of our app.

To get examples of these designs you can copy the code from pages like `/dashboard/settings`, that has lots of cards.

If you would like to keep working on it could I request we follow the designs of [daisy ui](https://daisyui.com/components/card/) rather than making our own.

Thanks bud though, I appreciate your interest. We should maybe come up with an `eraser.io` / sketch of the design first so we can get a good layout/show the right details.

But that's up to you, if you don't want to work on this anymore let me know, thanks man! 😀

**Comment by JonasFiechter** [comment]
Hi @TreyWW, output file was edit manually by me, there was some details missing, I just followed the same patterns.

There is no problem at all with the changes requested, at least by my side. If you are in a hurry to make this work with another dev just let me know and I can jump over to another issue. Otherwise I will try to follow the steps request this weekend and add a new PR soon. I am really enjoying being part of this proj. 

Thank you for your patience!

**Comment by JonasFiechter** [comment]
Hi @TreyWW Unfortunately I couldn't work in the project the last few days, but I plan to finish the first steps by this weekend;

Do you have an Idea about what data should we bring to the dashboard, following the last template I've added some generic stuff like:
- Overview (with some cool graphic stuff about the actual month)
- Income / goal
- Expenses / goal
- Last transactions (the last model I've added the receipt column with a 'href' pointing to the receipt related to it)
So the amount of data shown and witch of then is crucial to at least know how the cards will be.
If that's enough for now I'll start building the cards following the instructions you gave me, if not please, fell free to share.

**Comment by JonasFiechter** [comment]
I'll also provide a sketch with the template with the desired data into the cards for approval before start building;

**Pull request closed without merging**
