### PR TITLE
integrates the CONTRIBUTING.md to README.md

### LINKED ISSUE #1: [FEATURE] Login
basic login

## Preconditions:
Basic login page, with forgot password option

## Acceptance Criteria:
- Working logins
- Only visit when not logged in
- Cannot view index
- must have a basic "main page" which anyone can visit, not linked to dashboard

## Definition of Done:
- [x]  login is functional
- [x] only visit when not logged in
- cannot view index (moved to #13, cause i dont yet have an index)
- [x]  code has been tested
- [x] all tasks are completed

### PR DESCRIPTION
**Pull request by Z3nKrypt**
## Overview

This PR integrates the content of `CONTRIBUTING.md` into `README.md` to provide users with a more streamlined and consolidated guide on how to contribute to the project. This change makes it easier for new contributors to understand the contribution process without having to navigate between multiple files.

## Changes

- Merged the content of `CONTRIBUTING.md` into the "Contributing" section of `README.md`.
- Reformatted and rephrased some sections for clarity and coherence within the `README.md` structure.
- Updated relevant links to ensure they point to the correct sections or external resources.

Resolves #1.

### CODE REVIEW

**Comment by TreyWW** [comment]
Hi there, 
Thanks for taking interest in my first open-source project.
I see that you closed the pull request, do you not think this should be added? I agree with you if you think this would be a good change.

Thanks again

**Comment by Z3nKrypt** [comment]
Hi @TreyWW , 
i was a bit unsure. But now I reopened it. Maybe it would help to have it straight in the README.md
Best!

**Comment by Z3nKrypt** [comment]
Thanks for the merge. How can i find you on discord?

**Comment by TreyWW** [comment]
Hiya, my username is "ospam" all lowercase.

**Comment by Z3nKrypt** [comment]
It says that you don't accept friend requests. Try mine: __jakob___

**Comment by TreyWW** [comment]
Sorry about that, we're not in any common servers and my profile blocks that. My bad. I've added you.

**Comment by Z3nKrypt** [comment]
Sorry, I think it was the wrong one, because Github automatically changed my username. Please try this: "__jakob___"

**Pull request merged**
