### PR TITLE
Remove currency conversion

### LINKED ISSUE #460: idea: Remove currency conversion
### How big is this feature?

Small

### Describe the problem

It's a tiny feature, no purpose, more hassle. 

### Describe a possible solution

_No response_

### PR DESCRIPTION
**Pull request by vatsaaaal**
## Description

This pull request removes the currency conversion feature from the project, which includes:

- Removing all frontend, backend, and API files related to the currency converter.
- Removing the test files associated with the currency converter.
- Removing the 'forex-python' dependency from the 'pyproject.toml' file.
- Running 'poetry update' to update dependencies.

### Motivation

The currency conversion feature was deemed to have no significant purpose and caused more hassle than benefit, as per issue #460 .

### Dependencies

No new dependencies are required for this change.

# Checklist

- [x] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [x] Made any changes or additions to the documentation _where required_
- [x] Changes generate no new warnings/errors
- [x] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- 🐛 Bug Fix
- ♻️ Code Refactor

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc

- Closes #460

### CODE REVIEW

**Comment by TreyWW** [comment]
Hey @vatsaaaal,

Welcome to the project, and thanks for the contribution! I'll review (+ hopefully merge) the PR tomorrow afternoon, I've got a few things planned for the morning

**Comment by vatsaaaal** [comment]
Thank you. Sounds good @TreyWW !

**Comment by TreyWW** [comment]
Apologies for the delay, I went away and didn't have a chance to review this before. I'm back now, just going to finish my PR then I'll get back to this. Hopefully within the next 2 days. Thanks again for the contribution and patience

**Comment by vatsaaaal** [comment]
Okay, no worries.

**Review by TreyWW — APPROVED** [review]

**Comment by TreyWW** [comment]
Thanks again for the PR, really appreciate it! 💜

**Pull request merged**
