### PR TITLE
[BIG REVAMP] Public API + Service Layer (#409)

### LINKED ISSUE #409: Public API
Soon we'll want some form of Public API. This allows customers to, if they wish, expand on our frontend/add integrations, to make the most out of our project. We will use django-rest-framework.

So we'll want two forms of "APIs".

1. Internal HTMX API - allows frontend to call backend parts without page loads
2. public API - json based allows customers or external apps to use our backend

For the public API we'll need a form of authentication; possibly JWT with API Keys rather than allowing direct user access.

More details will come shortly, if you'd like to help with this feature, please do add a comment below!

### PR DESCRIPTION
**Pull request by TreyWW**
## Description

We are going to change the whole of the project to use a Service Layer type approach along with 3 access points.

- Main website view
- HTMX Internal API
- Public JSON-Based API

Instead of duplicating code throughout the main view and public json view, we'll introduce a service layer. All core features, e.g. creating a client in the DB, validating input, will be shared.

# Checklist

- [x] Make sure authentication for the Public API is tested and works well
- [x] Make sure you can generate public api keys from the MyFinances main dashboard
- [x] Make sure ALL views have references to the service layer
- [x] Make sure ALL core endpoints have a related Public API endpoint

# Related Issues
- closes #409 

# Shared Tasks
- [x] Clients @TreyWW 
- [x] Invoices @Domejko

### CODE REVIEW

**Comment by Domejko** [comment]
I started working on **Invoices**.

**Comment by TreyWW** [comment]
By the way @Domejko to see the UI you can use `http://127.0.0.1:8000/swagger/` for interactive API or `http://127.0.0.1:8000/redoc/` for just a "documentation" style

**Comment by TreyWW** [comment]
# todo
- [ ] add auto swagger decorator to /invoices/create
- [ ] add auto swagger decorator to /invoices/add_service
- [ ] add auto swagger decorator to /invoices/delete
- [ ] add auto swagger decorator to all of /invoices/edit/*
- [ ] add auto swagger decorator to /invoices/set_destination/*
- [ ] change /invoices/edit/ method to PUT
- [ ] add "mark as" endpoint for invoices

**Comment by TreyWW** [comment]
Add permission system for public api!

**Comment by TreyWW** [comment]
Big, big, thank you to @Domejko. I really appreciate your help with this feature.

**Pull request merged**
