### PR TITLE
Query issue fix

### LINKED ISSUE #267: performance bug: Causing extra user queries
### What version of MyFinances are you currently using?

latest (main)

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

At the moment we're using 2 queries for each request due to our custom user manager

### PR DESCRIPTION
**Pull request by Domejko**
## Description

Regarding #267 
- Refactored CustomUserMiddleware to replace AuthenticationMiddleware
- Removed CustomUserMiddleware from *backend/models.py* and placed it in *backend/middleware.py*
- In *settings/settings.py* replaced `"django.contrib.auth.middleware.AuthenticationMiddleware"` with `"backend.middleware.CustomUserMiddleware"`

# Checklist

- [x] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [x] Made any changes or additions to the documentation _where required_
- [x] Changes generate no new warnings/errors
- [x] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- 🐛 Bug Fix

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #
- Closes #267

### CODE REVIEW

**Comment by TreyWW** [comment]
Oh i've just seen what you mean, in our middleware we dont even call the additional fetch for profile. Maybe it's somewhere else. I'll check it out now, i could've swore it was here

**Comment by TreyWW** [comment]
Ah this is what I was thinking of https://github.com/TreyWW/MyFinances/blob/main/backend/models.py#L41

**Comment by Domejko** [comment]
Problem is that both `AuthenticationMiddleware` and `CustomUserMiddleware` where using query to fetch the user object. I removed `AuthenticationMiddleware` from `MIDDLEWARE` and adjusted `CustomUserMiddleware` so that it would replace it and populate `request.user` with our CustomUser instance.

With this changes we don't get double query issue and user profile is also accessible in `request.user`.

**Comment by TreyWW** [comment]
Amazing. Does this pass all tests still and everything visually work on the site? Just wondering if any Django packages use the middleware or if they will automatically move over to our new one

**Comment by Domejko** [comment]
Yes it was passing tests on my machine and on website everything work as intended. As for `AuthenticationMiddleware` I did check and it looks like it's not used anywhere else in Django.

I will fix that mypy error and will push that PR.

**Comment by TreyWW** [comment]
Thanks @Domejko, really appreciate the support recently!

**Pull request merged**
