### PR TITLE
Remove Precommits

### PR DESCRIPTION
**Pull request by TreyWW**
I believe pre-commits are a nightmare. They slow down development, sometimes cause issues that fully block users from committing (have done this to me many times!) and just don't seem worth it.

We have PR status checks that will block things like linting issues. I'd rather allow users to commit and then guide them to fix issues rather than not letting them commit and be stuck on their own.

### CODE REVIEW

**Comment by TreyWW** [comment]
- [ ] needs to remove poetry deps

**Comment by Domejko** [comment]
Maybe better solution would be to keep just basic ones like black, djlint/prettier and mypy. I would also consider swapping djLint to [Prettier]( https://prettier.io/docs/en/) it's much more popular, active and up to date in compare to djLint and covers more formats like css/js/md/yaml. I could implement that but for that to work HTML code need to be fixed because it's a mess, double quotes used everywhere like here
```
hx-get="{% url "api:base:modal retrieve with context" modal_name="leave_team" context_type="leave_team" context_value=team.id %}"
```
this cause problems for linting/formatting tools.

**Comment by TreyWW** [comment]
Does prettier support Django templates though @Domejko?

**Comment by Domejko** [comment]
There is jinja2 plugin.

**Comment by Domejko** [comment]
Hmm so we could leave it with just Black and for djLint change command to --format instead of --check (to avoid getting blocked by djLint errors) and I could start working on replacing djLint with Prettier but it will take some time since there are dozens of errors in html that have to be fixed before it will be able to run properly.

**Comment by TreyWW** [comment]
Is there any direct issues with djlint though? I've found it to work wonders. You can also change config to make " turn into single ' but I just had it off cause it's habit to use double quotes lol. We can change some config to make it better, it's a great tool

**Comment by Domejko** [comment]
Yes but I think it will just replace all " with ' and the issue is that " are used inside " what makes code look like this :
Screenshot from 2024-05-29 13-01-05
Closing tag then is seen by IDE as orphan. All that is fixed and handled by browser either way but for the esthetic part and readability it's a stench.

As to djLint vs Prettier I just find Prettier formatting style cleaner plus what I have already mentioned it covers much more formats like js/css/yaml/md what makes just a whole project more standardized/unified. It's also much bigger tool used in almost 8 million repos that is updated much more often and I see it as just having better perspectives for long term use and constants tool improvement.

**Comment by TreyWW** [comment]
Decided to optimise pre-commits rather then remove them fully. Great ideas @Domejko. As for prettier, I have made a discussion #396 and I'll come back to it at some point - I dont think its too necessary right now.

**Comment by TreyWW** [comment]
(moved to #395)

**Pull request closed without merging**
