### PR TITLE
FIX - Issue 304.

### LINKED ISSUE #304: progress: Invoices->Actions menu is under other template
### What version of MyFinances are you currently using?

v0.3.0

### What device type are you currently facing the issue on?

Desktop

### Describe the bug

The first invoice menu actions work good. The second and the other have the bug.
The bug is in Mobile and Desktop
imagen
imagen

### PR DESCRIPTION
**Pull request by pvvramakrishnarao234**
## Description

Added a condition at /invoices/single so that last two invoices have a dropup and not go behind the parent container.

# Checklist

- [Yes] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks  will  fail without)
- [Not needed] Made any changes or additions to the documentation _where required_
- [No] Changes generate no new warnings/errors
- [No] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- 🐛 Bug Fix
- ♻️ Code Refactor

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #304 
- Closes #304

### CODE REVIEW

**Comment by TreyWW** [comment]
Awaiting filter removal from template

**Comment by pvvramakrishnarao234** [comment]
removed filters

**Comment by pvvramakrishnarao234** [comment]
Removed migration file

**Comment by pvvramakrishnarao234** [comment]
ok, got it

**Comment by TreyWW** [comment]
Yep seems to work well on mobile and desktop. Thanks for your first contribution @pvvramakrishnarao234, much appreciated! Let me know on discord if there's anything further you'd like to work on, there's a few interesting ideas i'll be implementing in the next few weeks so it's a good time to spot in :)

**Pull request merged**
