### PR TITLE
Added action to allow POST without JS

### LINKED ISSUE #376: bug: Logging in without HTMX gives error
### What version of MyFinances are you currently using?

latest

### What device type are you currently facing the issue on?

_No response_

### Describe the bug

image

If for whatever reason loading JS doesn't work, HTMX falls back to a post request, which doesn't work atm

### PR DESCRIPTION
**Pull request by Domejko**
## Description

Regarding #376 
- Added `action="{% url 'auth:login manual' %}"` to html form so that when JS is disabled code will default to `action` instead of using `hx`.

# Checklist

- [x] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [x] Made any changes or additions to the documentation _where required_
- [x] Changes generate no new warnings/errors
- [x] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- 🐛 Bug Fix
- ♻️ Code Refactor

## Added/updated tests?

- 🙅 no, because they aren't needed

## Related PRs, Issues etc
- Related Issue #
- Closes #376

### CODE REVIEW

**Comment by TreyWW** [comment]
This doesn't seem to be working. Did it work for you?

**Comment by TreyWW** [comment]
Ah; as we redirect when the user doesn't use HTMX this doesn't make sense to implement.

```py
    if not request.htmx:
        return redirect("auth:login")
```

As the user is just stuck with an infinite loop

**Comment by Domejko** [comment]
Yes, I just made it work in shape and form as it is now without errors.

Basically it comes down now to what's is the desired functionality ? Because if website is supposed to be fully functional without JS then we would need to refactor most of html files since many of them use `hx-*`, and some backend files also got checks for `request.htmx`. Without it many functions will just not work and I think that it would be a bad idea to give users access to half baked website.
If not then I would keep `if not request.htmx:` and additionally inform user that he have JS disabled and since this website use JS ask him to enable it. I assume that cases when someone try to use internet without JS are very extreme this days.

**Comment by TreyWW** [comment]
Yeah I agree with that. It's probably easier to just stick with the idea of users have to have JS enabled, otherwise like you say the whole site wont work. Every page (pretty much) has some reliability on HTMX, and I'd rather not have to make all of it work without it. Maybe a popup saying you need JS could be a good option - that way this bug wont ever occur. We could just add a message before we redirect them to help a little too

**Comment by Domejko** [comment]
@TreyWW I have added a popup with short info to enable JS and hyperlink to instructions how to do it on different browsers. It activates only when JS is disabled and someone enters login page. I didn't add possibility to close window since website either way wont be functional without JS.

Preview:
Screenshot from 2024-05-27 16-18-13

**Comment by TreyWW** [comment]
Nice, I'd rather we use DaisyUI and tailwind though please. Since they have built in components that will do this and will keep the colour theme synced and styling consistent

**Comment by Domejko** [comment]
I have utilized available classes to sync color, font theme and size. Only `.popup` class left since Tailwind don't provide popup class.

Preview:
Screenshot from 2024-05-27 17-16-32

**Review by TreyWW — APPROVED** [review]

**Pull request merged**
